#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

archs=(rm2)
pkgnames=(linux-mainline)
pkgdesc="reMarkable 2 Kernel based on the mainline kernel"
url=https://www.kernel.org
pkgver=5.17.0-1
timestamp=2021-10-28T19:41:07Z
section="devel"
maintainer="Alistair Francis <alistair@alistair23.me>"
makedepends=(build:flex build:bison build:libssl-dev build:bc build:lzop build:libgmp-dev build:libmpc-dev build:kmod)
license=GPL-2.0-only
flags=(nostrip)
installdepends=(kernelctl)
image=base:v2.2

source=("https://github.com/alistair23/linux/archive/2ef1f512f83a6322b484964eabe31b04a964b0e6.tar.gz")
sha256sums=(f691c7c50ef50bc9b35c1e180a59222d4b823e1da3f39db06757cd15e4fe3304)

build() {
    mkdir -p out/lib
    mkdir -p out/boot
    ARCH=arm make imx_v6_v7_defconfig
    ARCH=arm make -j8
    ARCH=arm make modules_install INSTALL_MOD_PATH="out/"
    cp arch/arm/boot/zImage out/boot/zImage
    cp arch/arm/boot/dts/imx7d-remarkable2.dtb out/boot/zero-sugar.dtb
    rm out/lib/modules/*/source
    rm out/lib/modules/*/build
}

package() {
    pushd "$srcdir"/out
    tar cpjf ../mainline-"$pkgver".tar.bz2 lib/modules/* boot/*
    popd
    install -D -m 644 -t "$pkgdir"/opt/usr/share/kernelctl "$srcdir"/mainline-"$pkgver".tar.bz2
}

configure() {
    echo "The new kernel files have been copied, but not installed"
    echo "Please use kernelctl to select the kernel to boot."
    echo ""
    echo "Known issues with the mainline kernel:"
    echo " - No support for low power mode (suspend uses more power then it should)"
    echo " - Waking from sleep can be unreliable"
    echo " - WiFi sometimes is off on boot (can be turned on in Oxide though)"
    echo " - GUI shutdown in Oxide doesn't work"
    echo " - Wacom stylus doesn't work in Xochitl (works everywhere else though)"
    echo " - No RDNIS (network) access over USB"
    echo " - No OTG control support"
}
